{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubelet-volume-stats-exporter.fullname" . }}
  namespace: {{ include "kubelet-volume-stats-exporter.serviceMonitor.namespace" . }}
  labels:
    {{- include "kubelet-volume-stats-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.serviceMonitor.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  selector:
    matchLabels:
      {{- include "kubelet-volume-stats-exporter.selectorLabels" . | nindent 6 }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
      path: /metrics
      scheme: http
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.targetLabels }}
      targetLabels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

